import { Router } from 'express';
import { Role } from '@prisma/client';
import { attendanceController } from './attendance.controller';
import { authenticate } from '../../middleware/auth.middleware';
import { authorizeRoles } from '../../middleware/role.middleware';
import { validateBody, validateQuery } from '../../middleware/validate.middleware';
import { attendanceScanRateLimiter } from '../../middleware/rateLimit.middleware';
import { resetScopeSchema, resetConfirmSchema, resetHistorySchema, openSessionSchema, closeSessionSchema, markAttendanceSchema, scanAttendanceSchema, sessionQuerySchema, rosterQuerySchema, todayAttendanceQuerySchema } from './attendance.schema';
const router = Router();
router.use(authenticate, authorizeRoles(Role.SUPER_ADMIN, Role.ADMIN, Role.TEACHER));
const administrators = authorizeRoles(Role.SUPER_ADMIN, Role.ADMIN);
const superAdmin = authorizeRoles(Role.SUPER_ADMIN);
router.post('/reset/preview', superAdmin, validateBody(resetScopeSchema), attendanceController.resetPreview);
router.post('/reset/confirm', superAdmin, attendanceScanRateLimiter, validateBody(resetConfirmSchema), attendanceController.resetConfirm);
router.get('/reset/history', superAdmin, validateQuery(resetHistorySchema), attendanceController.resetHistory);
router.post('/sessions', administrators, validateBody(openSessionSchema), attendanceController.open);
router.get('/sessions', validateQuery(sessionQuerySchema), attendanceController.list);
router.get('/sessions/:sessionId/candidates', validateQuery(rosterQuerySchema), attendanceController.candidates);
router.get('/sessions/:sessionId', attendanceController.detail);
router.post('/sessions/:sessionId/mark', attendanceScanRateLimiter, validateBody(markAttendanceSchema), attendanceController.mark);
router.post('/sessions/:sessionId/close', administrators, validateBody(closeSessionSchema), attendanceController.close);
// Compatibility writes still require an explicit examination session.
router.post('/scan', attendanceScanRateLimiter, validateBody(scanAttendanceSchema), attendanceController.scan);
router.get('/today', validateQuery(todayAttendanceQuerySchema), attendanceController.getToday);
router.get('/student/:id', validateQuery(rosterQuerySchema), attendanceController.getStudentHistory);
export default router;
