services:
  - type: web
    name: AZMNEW
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install --include=dev && npx prisma generate && npx puppeteer browsers install chrome && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: QR_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false
      - key: FRONTEND_URL
        sync: false
